
# coding: utf-8

# # Estimating the biomass of plants
# In order to estimate the biomass of plants, we rely on data generated by **Erb et al.**, which generated seven different estimates of the global biomass of plants. The seven estimates are:

# In[1]:


import pandas as pd
import numpy as np
from scipy.stats import gmean
import sys
sys.path.insert(0,'../statistics_helper/')
from CI_helper import *
pd.options.display.float_format = '{:,.1e}'.format
data = pd.read_excel('plant_data.xlsx', skiprows=1)
data['Total biomass estimate [g C]'] = data['Total biomass estimate [g C]'].astype(float)
data


# As best estimate of the total biomass of plants, we use the geometric mean of the seven different estimates:

# In[2]:


best_estimate = gmean(data['Total biomass estimate [g C]'])

print('Our best estimate for the biomass of plants is ≈%.1f Gt C' %(best_estimate/1e15))


# # Uncertainty analysis
# As noted in the plants section in the Supplementary Information, one possible strategy to assess the uncertainty associated with the estimate of the total biomass of plants is to calculate the 95% confidence interval around the best estimate:

# In[3]:


estimate_CI = geo_CI_calc(data['Total biomass estimate [g C]'])
print('The 95 percent confidence interval around our best estimate for the total biomass of plants is ≈%.1f-fold' %estimate_CI)


# In order to account for additional sources of uncertainty not captured by calculating the 95% confidence interval, we use the ratio between uper and lower most estimates relative to our best estimate as our best projection for the uncertainty associated with our estimate of the total biomass of plants:

# In[4]:


upper_CI = data['Total biomass estimate [g C]'].max()/best_estimate
lower_CI = best_estimate/data['Total biomass estimate [g C]'].min()

mul_CI = np.max([upper_CI,lower_CI])

print('Our best projection for the uncertainty associated with the estimate of the total biomass of plants is ≈%.1f-fold' %mul_CI)

